name: python-coralogix-sdk
CX_PRODUCT: cs
deployable_type: library
version: 0.1.0
code_language: python
language_versions: [ '3.5', '3.6', '3.7', '3.8']
tests: true
test_image_name: python-mirror
test_image_tag: "3.8"
public: true
test_reporter_id: 87c96e9a1b2a30209f61b5c1c257a1e27376c58af809dd780b4fb3baf3a2ede3